#!/bin/sh
mkdir -p headers
wget -O headers/stb_image.h https://raw.githubusercontent.com/nothings/stb/refs/heads/master/stb_image.h
wget -O headers/stb_truetype.h https://raw.githubusercontent.com/nothings/stb/refs/heads/master/stb_truetype.h